#!/bin/bash

##### VARIABLES #####

wait="sleep 0.4"
main_folder="$HOME/.kxprograms/updatefirm"
backup_main_folder="$HOME/.kxprograms/updatefirm/Firmware_Backup"
new_firmware_folder="$HOME/.kxprograms/updatefirm/linux-firmware"
old_firmware_folder="/lib/firmware"

##### FUNCTIONS #####

function updateF(){
     git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
     mkdir -p $main_folder
     mkdir -p $backup_main_folder
     mv linux-firmware $new_firmware_folder
     sudo cp -r $old_firmware_folder/* $backup_main_folder/ && $wait && sudo rm -R $old_firmware_folder/* && $wait && sudo cp -r $new_firmware_folder/* $old_firmware_folder/ && $wait && sudo rm -R -f $new_firmware_folder && sudo update-initramfs -u
     echo "Do you want to reboot? (Y/n)" && read input
     case $input in
          Y|y) sudo reboot
          ;;
          N|n) exit
          ;;
          *) sudo reboot
     esac
}
function backupF(){
     sudo rm -R $old_firmware_folder/* && $wait && sudo cp -r $backup_main_folder/* $old_firmware_folder/ && $wait && sudo rm -R $backup_main_folder
     echo "Do you want to reboot? (Y/n)" && read input
     case $input in
          Y|y) sudo reboot
          ;;
          N|n) exit
          ;;
          *) sudo reboot
     esac
}
function helpF(){
     echo "
  [INFORMATION]
  
    This script updates your firmware, based in GIT parameters.
    
  [USAGE]
    
    -h: prints this option
    -v: prints the version of the script
    -U: updates the firmware and creates a backup for a old one
    -B: backups the firmware
    
  [CAUTION]
    
    Don't use (-U) and (-B) flags in the same line!
     "
}
function versionF(){
     echo "  updatefirm 1.2 - KanuX-14 | 07/07/2020 ~ 6:32 PM"
}
while getopts ":hvUB" opt; do
     case $opt in
          h) helpF
          ;;
          v) versionF
          ;;
          U) updateF
          ;;
          B) backupF
          ;;
          *) echo "This option don't stand up here!"
          ;;
     esac
done
